version: '3.9'

services:

  eureka-server:
    container_name: "eureka-server"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PATH_FOLDER=./eureka-server
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 2m
      retries: 5
      start_period: 1m

  api-gateway:
    container_name: "api-gateway"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PATH_FOLDER=./api-gateway
    ports:
      - 8080:8080
    depends_on:
      eureka-server:
        condition: service_started

  activemq:
    image: rmohr/activemq
    container_name: "activemq"
    ports:
      - 61616:61616 # JMX
      - 8161:8161 # Web Console
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=512
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 2m
      retries: 5
      start_period: 1m

  product-service:
    container_name: "product-service"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PATH_FOLDER=./product-service
    ports:
      - 8045:8045
    depends_on:
      eureka-server:
        condition: service_started
      activemq:
        condition: service_started
      api-gateway:
        condition: service_started

  cart-service:
    container_name: "cart-service"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PATH_FOLDER=./cart-service
    ports:
      - 8050:8050
    depends_on:
      eureka-server:
        condition: service_started
      activemq:
        condition: service_started
      api-gateway:
        condition: service_started