server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8045
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: http://cart-service:8050
          predicates:
            - Path=/cart/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:9000/eureka